version: '3.8'

services:
  app:
    build: .
    container_name: cocos-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - cocos-net

  db:
    image: postgres:15
    container_name: cocos-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cocos_challange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cocos-net
  redis:
    image: redis:7
    container_name: cocos-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cocos-net
volumes:
  pgdata:

networks:
  cocos-net: