version: '3.8'

services:
  app:
    build: .
    container_name: cocos-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nest-net

  postgres:
    image: postgres:15
    container_name: cocos-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cocos_challange
      POSTGRES_USER: cocos_root
      POSTGRES_PASSWORD: root.!*
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-net

volumes:
  pgdata:

networks:
  nest-net: